### ISSUE TITLE
[Feature Request] Improve documentation

### ISSUE THREAD

**Issue by alexmozaidze** [HDictus/breezefield#15]
At the moment, there isn't much documentation on this library. Although, I'd consider it *kind of* a thin wrapper for Love's native physics engine, it's still a good idea to improve on documentation. Like, I had to look into the source code in order to find out the [callback names](https://github.com/HDictus/breezefield/blob/9d6fdaf98d81ea13c386f7c0ca11be780432a0bb/world.lua#L57) for object collisions.

So far I'm really enjoying the library, it really makes it easy to prototype in early stages of development. Thank you for making it!

**Comment by HDictus** [comment]
Thanks for your feedback alexmozaidze. You're right, not including the collisions in the README is a big oversight. I'll correct it this afternoon.

**Comment by HDictus** [comment]
see #18
