### ISSUE TITLE
[Feature Request] Specifying draw order

### ISSUE THREAD

**Issue by alexmozaidze** [HDictus/breezefield#16]
It would be quite useful to be able to specify draw order for objects. At the moment, one must implement draw ordering on his own, which basically restricts you from using `world:draw`, and it's quite unfortunate due to how simple it is to use.

**Comment by HDictus** [comment]
Good idea. Should be simple enough to do, just need to sort the list of colliders by some `order` attribute.

**Comment by HDictus** [comment]
see #17
