### ISSUE TITLE
How to set a max position for LinearImpulse?

### ISSUE THREAD

**Issue by tonmoy998** [HDictus/breezefield#21]
Sorry I am new to game development.I am practicing running game like browser's dinosaur game.So I need a fixed y value for jumping.And also need acceleration value for camera.Kindly suggest me some methods.

**Comment by HDictus** [comment]
Hi tonmoy. Sorry that I haven't been around. generally this is the sort of question you ask on the love2d forums, but in case you haven't gotten it figured out yourself I'll help you out. I think you mean that you want to set the y velocity to a specific value? love.physics does not support setting just the y velocity specifically, so you'll need to go through Collider:setLinearVelocity.

```
local vx, vy = collider:getLinearVelocity()
vy = JUMP_SPEED
collider:setLinearVelocity(vx, vy)
```

Cheers

**Comment by tonmoy998** [comment]
Thank you
